development:
   cloud_name: "mirjan"
   api_key: "898481618515398"
   api_secret: "-Ycck2fncK8RjLEz-oi0_JYgbGo"

production:
   cloud_name: "mirjan"
   api_key: "898481618515398"
   api_secret: "-Ycck2fncK8RjLEz-oi0_JYgbGo"

# development:
#    cloud_name: "my-books-images"
#    api_key: "157645628133455"
#    api_secret: "12qf5ycBU1zwD2RQ3Fpn39sb7Md"

# production:
#    cloud_name: "my-books-images"
#    api_key: "157645628133455"
#    api_secret: "12qf5ycBU1zwD2RQ3Fpn39sb7Md"

